#!/bin/env bash
OUTPUT=$(protonvpn-cli s)

if [[ $OUTPUT != "No active Proton VPN connection." ]]
then
    IP=$(echo "$OUTPUT" | grep "IP:" | awk '{print $2}')
    SERVER=$(echo "$OUTPUT" | grep "Server:" | awk '{print $2}')
    LOAD=$(echo "$OUTPUT" | grep "Server Load" | awk '{print $3}')
    
    echo "$IP@$SERVER [$LOAD]"
    echo "$SERVER"
    echo "#d335ff"
else 
    echo " NOT RUNNING"
    echo " NOT RUNNING"
    echo '#FF0000'
fi
